src/java/de/dhbw/lmf/addressbook/LoginBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package de.dhbw.lmf.addressbook;

import java.util.ArrayList;

/**
 *
 * @author Flo
 */
public class LoginBean {
    
    private ArrayList<User> users;
    private int loggedInUser;
    
    public LoginBean() {
        this.users = new ArrayList<User>();
        this.loggedInUser = -1;
        
        this.users.add(new User("admin", "test1234", UserType.ADMIN));
        this.users.add(new User("user", "test1234", UserType.USER));
    }
    
    public boolean isLoggedIn() {
        return (this.loggedInUser != -1);
    }
    
    public boolean isAdmin() {
        return (this.isLoggedIn() && this.users.get(this.loggedInUser).isAdmin());
    }
    
    public boolean login(String username, String passwort) {
        if (username.isEmpty() || passwort.isEmpty()) {
            this.loggedInUser = -1;
            return false;
        }
        
        int i = 0;
        for (User u : this.users) {
            if (u.getUsername().equals(username) && u.getPassword().equals(passwort)) {
                this.loggedInUser = i; 
                return true;
            }
            i++;
        }
        
        this.loggedInUser = -1;
        return false;
    }
    
    public String getUsername() {
        if (this.isLoggedIn()) {
            return this.users.get(this.loggedInUser).getUsername();
        }
        
        return "NOT LOGGED IN";
    }
    
    public void logout() {
        this.loggedInUser = -1;
    }
}

web/details.jsp
<%-- 
    Document   : details
    Created on : 05.05.2014, 16:13:42
    Author     : Florian
--%>

<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@include file="WEB-INF/jspf/securitycheck.jspf" %>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <%@include file="WEB-INF/jspf/headerIncludes.jspf" %>
    </head>
    <body>
        <div id="wrapper">
            <jsp:useBean id="adr" class="de.dhbw.lmf.addressbook.AdressBean" />
            <c:set var="success" value="${adr.load(param.id)}"/>
            <c:if test="${!success}">
                <b>Error:</b> ${adr.lastError}
            </c:if>
            <c:if test="${success}">
                <h2>${adr.addressform} ${adr.christianname} ${adr.name}</h2>
                <br>
                <table class="table table-striped">
                    <tr>
                        <th style="width: 10%;">Email:</th>
                        <td><a href="mailto:${adr.email}">${adr.email}</a></td>
                    </tr>
                    <tr>
                        <th>Phone:</th>
                        <td>${adr.phone}</td>
                    </tr>
                    <tr>
                        <th>Address:</th>
                        <td>
                            ${adr.street} ${adr.number}<br>
                            ${adr.postcode} ${adr.city}<br>
                            ${adr.country}<br>
                            <button class="btn btn-primary btn-xs" data-toggle="modal" data-target="#mapModal">
                              Show map
                            </button>                           
                        </td>
                    </tr>
                    <tr>
                        <th>Birthdate:</th>
                        <td>${adr.birthday}</td>
                    </tr>
                </table>
                <!-- Modal -->
                <div class="modal fade" id="mapModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h4 class="modal-title">${adr.addressform} ${adr.christianname} ${adr.name} lives at...</h4>
                      </div>
                      <div class="modal-body" style="height: 500px;">
                          <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.de/maps?hl=en&q=${adr.country} ${adr.postcode} ${adr.street} ${adr.number}&ie=UTF8&t=&z=17&iwloc=B&output=embed"></iframe>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>  
                <!-- End of Modal -->  
                    <c:if test="${auth.admin}">
                    <button class="btn btn-primary" onclick="location.href='form.jsp?id=${adr.id}'">Edit</button>
                </c:if>
            </c:if>            
            <button class="btn btn-default" onclick="location.href='index.jsp'">Back to list</button>
            
        </div>
    </body>
</html>

web/form.jsp
<%-- 
    Document   : form
    Created on : 05.05.2014, 16:13:42
    Author     : Florian
--%>

<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@include file="WEB-INF/jspf/securitycheck.jspf" %>
<c:if test="${!auth.admin}">
    <jsp:forward page="index.jsp"></jsp:forward>
</c:if>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <%@include file="WEB-INF/jspf/headerIncludes.jspf" %>
    </head>
    <body>
        <div id="wrapper">
            <jsp:useBean id="adr" class="de.dhbw.lmf.addressbook.AdressBean" />         
            <c:if test="${param.id != null}">  
                Edit entry
                <c:set var="loadSuccess" value="${adr.load(param.id)}"/> 
                <c:if test="${!loadSuccess}">
                    <div class="alert alert-danger">
                        Could not load contact Error: ${adr.lastError}
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    </div>
                </c:if>
            </c:if>
            <c:if test="${param.id == null}">
                New entry
            </c:if>
            <c:if test="${(param.act != null) && (param.act eq 'save')}">  
                <jsp:setProperty name="adr" property="id" param="id" />
                <jsp:setProperty name="adr" property="addressform" param="addressform" />
                <jsp:setProperty name="adr" property="birthday" param="birthday" />
                <jsp:setProperty name="adr" property="christianname" param="christianname" />
                <jsp:setProperty name="adr" property="city" param="city" />
                <jsp:setProperty name="adr" property="country" param="country" />
                <jsp:setProperty name="adr" property="email" param="email" />
                <jsp:setProperty name="adr" property="mobile" param="mobile" />
                <jsp:setProperty name="adr" property="name" param="name" />
                <jsp:setProperty name="adr" property="number" param="number" />
                <jsp:setProperty name="adr" property="phone" param="phone" />
                <jsp:setProperty name="adr" property="postcode" param="postcode" />
                <jsp:setProperty name="adr" property="street" param="street" />
                <c:set var="checkErrors" value="${adr.check()}"/>              
                <c:if test="${checkErrors.size() > 0}">
                    <div class="alert alert-danger">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        Could not save contact due to the following error/errors:
                        <ul>
                            <c:forEach items="${checkErrors}" var="err">
                                <li>${err.toString()}</li>
                            </c:forEach>
                        </ul>                  
                    </div>
                </c:if>     
                <c:if test="${checkErrors.size() == 0}">
                    <c:set var="saveSuccess" value="${adr.save()}"/> 
                    <c:if test="${saveSuccess}">
                        <div class="alert alert-success">
                            Successfully saved! 
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        </div>
                    </c:if>                
                    <c:if test="${!saveSuccess}">
                        <div class="alert alert-danger">
                            Error during saving: ${adr.lastError}
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        </div>
                    </c:if>                       
                </c:if>                    
            </c:if>
            <form method="GET">
                <input type="hidden" name="act" value="save"> 
                <c:if test="${param.id != null}">
                    <input type="hidden" name="id" value="${param.id}">
                </c:if>
                <div class="form-group">
                  <div class="col-md-4">
                      <label>Addressform</label>
                      <input type="text" class="form-control" name="addressform" placeholder="Addressform" value="${adr.addressform}">
                  </div>
                  <div class="col-md-4">
                      <label>Christianname</label>
                      <input type="text" class="form-control" name="christianname" placeholder="Christianname" value="${adr.christianname}">
                  </div>    
                  <div class="col-md-4">
                      <label>Name</label>
                      <input type="text" class="form-control" name="name" placeholder="Name" value="${adr.name}">
                  </div>
                </div>
                <div class="form-group col-md-12">
                  <label>Email</label>
                  <input type="text" class="form-control" name="email" placeholder="Email" value="${adr.email}">
                </div>
                <div class="form-group">
                  <div class="col-md-6">
                    <label>Phone</label>
                    <input type="text" class="form-control" name="phone" placeholder="Phone" value="${adr.phone}">
                  </div>
                  <div class="col-md-6">
                    <label>Mobile</label>
                    <input type="text" class="form-control" name="mobile" placeholder="Mobile" value="${adr.mobile}">
                  </div>                    
                </div>  
                <div class="form-group">
                  <div class="col-md-6">
                    <label>Postcode</label>
                    <input type="text" class="form-control" name="postcode" placeholder="Postcode" value="${adr.postcode}">
                  </div>
                  <div class="col-md-6">
                    <label>City</label>
                    <input type="text" class="form-control" name="city" placeholder="City" value="${adr.city}">
                  </div>     
                  <div class="col-md-5">
                    <label>Street</label>
                    <input type="text" class="form-control" name="street" placeholder="Street" value="${adr.street}">
                  </div>
                  <div class="col-md-2">
                    <label>Number</label>
                    <input type="text" class="form-control" name="number" placeholder="Number" value="${adr.number}">
                  </div>      
                  <div class="col-md-5">
                    <label>Country</label>
                    <input type="text" class="form-control" name="country" placeholder="Country" value="${adr.country}">
                  </div>                    
                </div>
                <div class="form-group col-md-12">
                  <label>Birthday</label>
                  <input type="text" class="form-control" name="birthday" placeholder="dd.mm.yyyy" value="${adr.birthday}">
                </div>   
                <button type="submit" class="btn btn-primary">
                    <c:if test="${param.id == null}">Create new</c:if>
                    <c:if test="${param.id != null}">Save changes</c:if>
                </button>
            </form>
            <button class="btn btn-default" onclick="location.href='index.jsp'">Back to list</button>
        </div>
    </body>
</html>

web/index.jsp
<%-- 
    Document   : index
    Created on : 05.05.2014, 09:37:47
    Author     : Florian
--%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@include file="WEB-INF/jspf/securitycheck.jspf" %>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <%@include file="WEB-INF/jspf/headerIncludes.jspf" %>
    </head>
    <body>
        <div id="wrapper">
            <h1>Addressbook</h1>
            <h4>by Maurice Busch, Lukas Schreck and Florian Loch</h4>
            <br>
            <form class="form-inline">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" placeholder="Search for contact...">
                </div>
                <button type="submit" class="btn btn-default">Go</button>
            </form>
            <br>
            <c:if test="${(param.act != null) && (param.id != null) && (param.act eq 'del') && (auth.admin)}">
                <jsp:useBean id="adr" class="de.dhbw.lmf.addressbook.AdressBean" />
                <jsp:setProperty name="adr" property="id" value="${param.id}" />
                <c:set var="deleteSuccess" value="${adr.delete()}" />
                <c:if test="${deleteSuccess}">
                    <div class="alert alert-success">
                        Successfully deleted contact!
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    </div>
                </c:if>
                <c:if test="${!deleteSuccess}">
                    <div class="alert alert-danger">
                        An error occured during deletion: ${adr.lastError}
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    </div>
                </c:if>
            </c:if>
            
            <jsp:useBean id="list" class="de.dhbw.lmf.addressbook.AdressListBean" />
            <jsp:setProperty name="list" property="nameFilter" param="q" />
            <c:set var="success" value="${list.search()}" />
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Name</th><th>E-Mail</th><th></th>
                    </tr>
                </thead>
                <tbody>
                    <c:forEach items="${list}" var="adr">
                        <tr>
                            <td>${adr.addressform} ${adr.christianname} ${adr.name}</td>
                            <td>${adr.email}</td>
                            <td><a href="details.jsp?id=${adr.id}">Details</a> <a href="index.jsp?act=del&id=${adr.id}">Delete</a></td>
                        </tr>
                    </c:forEach>
                </tbody>
            </table>
            <c:if test="${auth.admin}">
                <button class="btn btn-primary" onclick="location.href='form.jsp';">Add new contact</button>
            </c:if>
        </div>
    </body>
</html>

web/login.jsp
<%-- 
    Document   : login
    Created on : 25.05.2014, 18:53:30
    Author     : Flo
--%>

<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8" %>

<jsp:useBean class="de.dhbw.lmf.addressbook.LoginBean" id="auth" scope="session"></jsp:useBean>
<c:if test="${(param.username != null) && (param.password != null)}">
    <c:set var="loginSuccessful" value="${auth.login(param.username, param.password)}"></c:set>
    <c:if test="${loginSuccessful}">
        <jsp:forward page="index.jsp"></jsp:forward>
    </c:if>
</c:if>
<c:if test="${(!empty param.act) && (param.act eq 'logout') && (auth.loggedIn)}">
    ${auth.logout()}
    Successfully logged out!
</c:if>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <%@include file="WEB-INF/jspf/headerIncludes.jspf" %>
    </head>
    <body>
        <div class="col-md-6 col-md-offset-3" style="margin-top: 40px;">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Login to "Adressbuch2"
                </div>
                <div class="panel-body">
                    <form method="POST">
                        <div class="form-group center-block"> 
                            <input type="text" name="username" class="form-control" placeholder="Username">
                        </div>
                        <div class="form-group center-block"> 
                            <input type="password" name="password" class="form-control" placeholder="Password">
                        </div>
                        <div class="form-group center-block">
                            <input type="submit" class="btn btn-primary center-block">
                        </div>
                    </form>  
                </div>
            </div>
        </div>
    </body>
</html>